#!/bin/bash
# /etc/init.d/mehdoh

### BEGIN INIT INFO
# Provides:          mehdoh
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       This service is used to manage the mehdoh q-municate chat xmpp bot
### END INIT INFO

case "$1" in
    start)
        echo "Starting mehdoh bot"
        python /home/pi/MehDoh-q-municate-chat-xmpp-bot/rundoh.py &
        ;;
    stop)
        echo "Stopping mehdoh bot"
        sudo pkill -f rundoh
        ;;
    *)
        echo "Usage: /etc/init.d/mehdoh start|stop"
        exit 1
        ;;
esac

exit 0